### ISSUE TITLE
Build fails on both x86/64 and on a Raspberry Pi 4B (winegcc) [Ubuntu 20.04 & 20.10]

### ISSUE THREAD

**Issue by pseudofunizer** [AndreRH/hangover#109]
Hi there,

I've been trying to get Hangover to compile on both a Ubuntu 20.10 system that runs on x86/64 (amd64) and on my Raspberry Pi 4B that is running Ubuntu 20.04 LTS, with the process failing on the exactly same stage with each of the machines. This a few `make -j4` (or `-j8`) commands into the overall process:

```
$ make -j8

make -C build/qemu
make[1]: Entering directory '/home/ubuntu/builds/hangover/build/qemu'
  CC      x86_64-windows-user/gdbstub-xml.o
  CC      x86_64-windows-user/windows-user/main.o
  CC      x86_64-windows-user/windows-user/mmap.o
  CC      x86_64-windows-user/windows-user/pe.o
  CC      x86_64-windows-user/windows-user/win_syscall.o
  CC      x86_64-windows-user/windows-user/signal.o
  CC      x86_64-windows-user/trace/generated-helpers.o
/home/ubuntu/builds/hangover/qemu/windows-user/win_syscall.c:22:10: fatal error: wine/library.h: No such file or directory
   22 | #include <wine/library.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
winegcc: /usr/bin/gcc failed
make[2]: *** [/home/ubuntu/builds/hangover/qemu/rules.mak:69: windows-user/win_syscall.o] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/ubuntu/builds/hangover/qemu/windows-user/main.c:26:10: fatal error: wine/library.h: No such file or directory
   26 | #include <wine/library.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
winegcc: /usr/bin/gcc failed
make[2]: *** [/home/ubuntu/builds/hangover/qemu/rules.mak:69: windows-user/main.o] Error 2
/home/ubuntu/builds/hangover/qemu/windows-user/pe.c:31:10: fatal error: wine/library.h: No such file or directory
   31 | #include <wine/library.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
winegcc: /usr/bin/gcc failed
make[2]: *** [/home/ubuntu/builds/hangover/qemu/rules.mak:69: windows-user/pe.o] Error 2
make[1]: *** [Makefile:527: x86_64-windows-user/all] Error 2
make[1]: Leaving directory '/home/ubuntu/builds/hangover/build/qemu'
make: *** [Makefile:183: build/qemu/x86_64-windows-user/qemu-x86_64.exe.so] Error 2
```

Oh well, at least it's not a clang error this time :o) All help appreciated.

**Comment by stefand** [comment]
Make sure your git submodules are up to date. There might also be a problem with my rebase that was conceiled by a wine/library.h in /usr/local/include on my system.

**Comment by simon-i1-h** [comment]
wine/library.h has been deleted on https://github.com/wine-mirror/wine/commit/a9a08dbc3dd8b595888f6c6b066e6c8fd389771a. I made the patch (https://github.com/AndreRH/qemu/pull/3).

**Comment by AndreRH** [comment]
yes, current build is broken, see also the badgets in the Readme

**Comment by pseudofunizer** [comment]
> yes, current build is broken, see also the badgets in the Readme

So... Is there a workaround for this at the moment, or is Hangover just simply broken and that's that? I just re-fetched the entire git along with submodules, tried compiling again and it failed at the same exact spot.

**Comment by AndreRH** [comment]
Try the latest tagged version

**Comment by AndreRH** [comment]
Fixed by 672728c4671098762d2ddce651042a74864aa891
